---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repo-url
    - name: branch
      default: main
  tasks:
    - name: init
      workspaces:
        - name: source
          workspace: pipeline-workspace          
      taskRef:
        name: cleanup

    - name: fix-permissions
      workspaces:
        - name: output
          workspace: pipeline-workspace
      taskSpec:
        steps:
          - name: fix-permissions
            image: busybox
            script: |
              #!/bin/sh
              echo "Fixing permissions on /workspace/output..."
              ls -ld /workspace/output
              chown -R 0:0 /workspace/output
              chmod -R 777 /workspace/output
            securityContext:
              runAsUser: 0   # ✅ Run as root to modify permissions
      runAfter:
        - init

    - name: clone
      workspaces:
        - name: output
          workspace: pipeline-workspace          
      taskRef:
        name: git-clone
      params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.branch)
      runAfter:
        - fix-permissions  # ✅ Ensures permissions are set before cloning

    - name: lint
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: flake8
      params:
        - name: image
          value: python:3.9-slim
        - name: args
          value: ["--count", "--max-complexity=10", "--max-line-length=127", "--statistics"]
      runAfter:
        - clone  # ✅ Ensures linting runs after cloning

    - name: tests
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: nose
      params:
        - name: image
          value: python:3.9-slim
        - name: database_uri
          value: "sqlite:///test.db"
        - name: args
          value: ["-v --with-spec --spec-color"]
      runAfter:
        - clone  # ✅ Ensures tests run after cloning
