apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipelinerun-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: crc-csi-hostpath-provisioner
  hostPath:
    path: "/mnt/data"
